global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'nextjs'
    metrics_path: '/api/metrics'
    scrape_interval: 10s
    static_configs:
      - targets: ['nextjs:3000']
        labels:
          service: 'nextjs'
          environment: 'development'
